name: Sborka
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - run: brew install cmake libomp rust
      - run: chmod +x ./run.sh && ./run.sh build
      - run: cd build/Build/Products/Debug && ditto -c -k --keepParent OpenSuperWhisper.app /tmp/OpenSuperWhisper.zip
      - uses: actions/upload-artifact@v4
        with:
          name: OpenSuperWhisper
          path: /tmp/OpenSuperWhisper.zip
          retention-days: 14
